# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='api',
  syntax='proto3',
  serialized_pb=_b('\n\tapi.proto\x12\x03\x61pi\"W\n\x0bInitRequest\x12\x10\n\x08\x63ustomer\x18\x01 \x01(\t\x12\x14\n\x0csolutionSize\x18\x02 \x01(\x05\x12\x0e\n\x06\x65valNb\x18\x03 \x01(\x05\x12\x10\n\x08solution\x18\x04 \x01(\t\"/\n\x0f\x46itnessResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08solution\x18\x02 \x01(\t\"-\n\x0e\x46itnessRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x66itness\x18\x02 \x01(\x01\"*\n\x0bStopRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"=\n\x0cStopResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08solution\x18\x02 \x01(\t\x12\x0f\n\x07\x66itness\x18\x03 \x01(\x01\x32\xca\x01\n\x13OperationalResearch\x12<\n\x10InitConversation\x12\x10.api.InitRequest\x1a\x14.api.FitnessResponse\"\x00\x12:\n\x0bSendFitness\x12\x13.api.FitnessRequest\x1a\x14.api.FitnessResponse\"\x00\x12\x39\n\x10StopConversation\x12\x10.api.StopRequest\x1a\x11.api.StopResponse\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INITREQUEST = _descriptor.Descriptor(
  name='InitRequest',
  full_name='api.InitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer', full_name='api.InitRequest.customer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='solutionSize', full_name='api.InitRequest.solutionSize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='evalNb', full_name='api.InitRequest.evalNb', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='solution', full_name='api.InitRequest.solution', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=105,
)


_FITNESSRESPONSE = _descriptor.Descriptor(
  name='FitnessResponse',
  full_name='api.FitnessResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='api.FitnessResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='solution', full_name='api.FitnessResponse.solution', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=154,
)


_FITNESSREQUEST = _descriptor.Descriptor(
  name='FitnessRequest',
  full_name='api.FitnessRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='api.FitnessRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fitness', full_name='api.FitnessRequest.fitness', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=201,
)


_STOPREQUEST = _descriptor.Descriptor(
  name='StopRequest',
  full_name='api.StopRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='api.StopRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='api.StopRequest.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=245,
)


_STOPRESPONSE = _descriptor.Descriptor(
  name='StopResponse',
  full_name='api.StopResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='api.StopResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='solution', full_name='api.StopResponse.solution', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fitness', full_name='api.StopResponse.fitness', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=308,
)

DESCRIPTOR.message_types_by_name['InitRequest'] = _INITREQUEST
DESCRIPTOR.message_types_by_name['FitnessResponse'] = _FITNESSRESPONSE
DESCRIPTOR.message_types_by_name['FitnessRequest'] = _FITNESSREQUEST
DESCRIPTOR.message_types_by_name['StopRequest'] = _STOPREQUEST
DESCRIPTOR.message_types_by_name['StopResponse'] = _STOPRESPONSE

InitRequest = _reflection.GeneratedProtocolMessageType('InitRequest', (_message.Message,), dict(
  DESCRIPTOR = _INITREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.InitRequest)
  ))
_sym_db.RegisterMessage(InitRequest)

FitnessResponse = _reflection.GeneratedProtocolMessageType('FitnessResponse', (_message.Message,), dict(
  DESCRIPTOR = _FITNESSRESPONSE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.FitnessResponse)
  ))
_sym_db.RegisterMessage(FitnessResponse)

FitnessRequest = _reflection.GeneratedProtocolMessageType('FitnessRequest', (_message.Message,), dict(
  DESCRIPTOR = _FITNESSREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.FitnessRequest)
  ))
_sym_db.RegisterMessage(FitnessRequest)

StopRequest = _reflection.GeneratedProtocolMessageType('StopRequest', (_message.Message,), dict(
  DESCRIPTOR = _STOPREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.StopRequest)
  ))
_sym_db.RegisterMessage(StopRequest)

StopResponse = _reflection.GeneratedProtocolMessageType('StopResponse', (_message.Message,), dict(
  DESCRIPTOR = _STOPRESPONSE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.StopResponse)
  ))
_sym_db.RegisterMessage(StopResponse)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class OperationalResearchStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.InitConversation = channel.unary_unary(
          '/api.OperationalResearch/InitConversation',
          request_serializer=InitRequest.SerializeToString,
          response_deserializer=FitnessResponse.FromString,
          )
      self.SendFitness = channel.unary_unary(
          '/api.OperationalResearch/SendFitness',
          request_serializer=FitnessRequest.SerializeToString,
          response_deserializer=FitnessResponse.FromString,
          )
      self.StopConversation = channel.unary_unary(
          '/api.OperationalResearch/StopConversation',
          request_serializer=StopRequest.SerializeToString,
          response_deserializer=StopResponse.FromString,
          )


  class OperationalResearchServicer(object):

    def InitConversation(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def SendFitness(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def StopConversation(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_OperationalResearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'InitConversation': grpc.unary_unary_rpc_method_handler(
            servicer.InitConversation,
            request_deserializer=InitRequest.FromString,
            response_serializer=FitnessResponse.SerializeToString,
        ),
        'SendFitness': grpc.unary_unary_rpc_method_handler(
            servicer.SendFitness,
            request_deserializer=FitnessRequest.FromString,
            response_serializer=FitnessResponse.SerializeToString,
        ),
        'StopConversation': grpc.unary_unary_rpc_method_handler(
            servicer.StopConversation,
            request_deserializer=StopRequest.FromString,
            response_serializer=StopResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'api.OperationalResearch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaOperationalResearchServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def InitConversation(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def SendFitness(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def StopConversation(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaOperationalResearchStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def InitConversation(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    InitConversation.future = None
    def SendFitness(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    SendFitness.future = None
    def StopConversation(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    StopConversation.future = None


  def beta_create_OperationalResearch_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('api.OperationalResearch', 'InitConversation'): InitRequest.FromString,
      ('api.OperationalResearch', 'SendFitness'): FitnessRequest.FromString,
      ('api.OperationalResearch', 'StopConversation'): StopRequest.FromString,
    }
    response_serializers = {
      ('api.OperationalResearch', 'InitConversation'): FitnessResponse.SerializeToString,
      ('api.OperationalResearch', 'SendFitness'): FitnessResponse.SerializeToString,
      ('api.OperationalResearch', 'StopConversation'): StopResponse.SerializeToString,
    }
    method_implementations = {
      ('api.OperationalResearch', 'InitConversation'): face_utilities.unary_unary_inline(servicer.InitConversation),
      ('api.OperationalResearch', 'SendFitness'): face_utilities.unary_unary_inline(servicer.SendFitness),
      ('api.OperationalResearch', 'StopConversation'): face_utilities.unary_unary_inline(servicer.StopConversation),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_OperationalResearch_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('api.OperationalResearch', 'InitConversation'): InitRequest.SerializeToString,
      ('api.OperationalResearch', 'SendFitness'): FitnessRequest.SerializeToString,
      ('api.OperationalResearch', 'StopConversation'): StopRequest.SerializeToString,
    }
    response_deserializers = {
      ('api.OperationalResearch', 'InitConversation'): FitnessResponse.FromString,
      ('api.OperationalResearch', 'SendFitness'): FitnessResponse.FromString,
      ('api.OperationalResearch', 'StopConversation'): StopResponse.FromString,
    }
    cardinalities = {
      'InitConversation': cardinality.Cardinality.UNARY_UNARY,
      'SendFitness': cardinality.Cardinality.UNARY_UNARY,
      'StopConversation': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'api.OperationalResearch', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
