# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

from . import hcfi_pb2 as hcfi__pb2


class OperationalResearchStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.InitConversation = channel.unary_unary(
        '/hcfi.OperationalResearch/InitConversation',
        request_serializer=hcfi__pb2.InitRequest.SerializeToString,
        response_deserializer=hcfi__pb2.FitnessResponse.FromString,
        )
    self.SendFitness = channel.unary_unary(
        '/hcfi.OperationalResearch/SendFitness',
        request_serializer=hcfi__pb2.FitnessRequest.SerializeToString,
        response_deserializer=hcfi__pb2.FitnessResponse.FromString,
        )
    self.StopConversation = channel.unary_unary(
        '/hcfi.OperationalResearch/StopConversation',
        request_serializer=hcfi__pb2.StopRequest.SerializeToString,
        response_deserializer=hcfi__pb2.StopResponse.FromString,
        )


class OperationalResearchServicer(object):

  def InitConversation(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendFitness(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StopConversation(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OperationalResearchServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'InitConversation': grpc.unary_unary_rpc_method_handler(
          servicer.InitConversation,
          request_deserializer=hcfi__pb2.InitRequest.FromString,
          response_serializer=hcfi__pb2.FitnessResponse.SerializeToString,
      ),
      'SendFitness': grpc.unary_unary_rpc_method_handler(
          servicer.SendFitness,
          request_deserializer=hcfi__pb2.FitnessRequest.FromString,
          response_serializer=hcfi__pb2.FitnessResponse.SerializeToString,
      ),
      'StopConversation': grpc.unary_unary_rpc_method_handler(
          servicer.StopConversation,
          request_deserializer=hcfi__pb2.StopRequest.FromString,
          response_serializer=hcfi__pb2.StopResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hcfi.OperationalResearch', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
