# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hcfi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hcfi.proto',
  package='hcfi',
  syntax='proto3',
  serialized_pb=_b('\n\nhcfi.proto\x12\x04hcfi\"v\n\x16InitTransactionRequest\x12\x10\n\x08\x63ustomer\x18\x01 \x01(\t\x12\x14\n\x0csolutionSize\x18\x02 \x01(\x05\x12\x0f\n\x07\x66itness\x18\x03 \x01(\x01\x12\x10\n\x08solution\x18\x04 \x01(\t\x12\x11\n\talgorithm\x18\x05 \x01(\t\"/\n\x0f\x46itnessResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08solution\x18\x02 \x01(\t\"?\n\x0e\x46itnessRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x66itness\x18\x02 \x01(\x01\x12\x10\n\x08solution\x18\x03 \x01(\t\"*\n\x0bStopRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"=\n\x0cStopResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08solution\x18\x02 \x01(\t\x12\x0f\n\x07\x66itness\x18\x03 \x01(\x01\x32\xd8\x01\n\x12HillClimberService\x12H\n\x0fInitTransaction\x12\x1c.hcfi.InitTransactionRequest\x1a\x15.hcfi.FitnessResponse\"\x00\x12<\n\x0bSendFitness\x12\x14.hcfi.FitnessRequest\x1a\x15.hcfi.FitnessResponse\"\x00\x12:\n\x0fStopTransaction\x12\x11.hcfi.StopRequest\x1a\x12.hcfi.StopResponse\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INITTRANSACTIONREQUEST = _descriptor.Descriptor(
  name='InitTransactionRequest',
  full_name='hcfi.InitTransactionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer', full_name='hcfi.InitTransactionRequest.customer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='solutionSize', full_name='hcfi.InitTransactionRequest.solutionSize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fitness', full_name='hcfi.InitTransactionRequest.fitness', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='solution', full_name='hcfi.InitTransactionRequest.solution', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='hcfi.InitTransactionRequest.algorithm', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=138,
)


_FITNESSRESPONSE = _descriptor.Descriptor(
  name='FitnessResponse',
  full_name='hcfi.FitnessResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hcfi.FitnessResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='solution', full_name='hcfi.FitnessResponse.solution', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=187,
)


_FITNESSREQUEST = _descriptor.Descriptor(
  name='FitnessRequest',
  full_name='hcfi.FitnessRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hcfi.FitnessRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fitness', full_name='hcfi.FitnessRequest.fitness', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='solution', full_name='hcfi.FitnessRequest.solution', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=252,
)


_STOPREQUEST = _descriptor.Descriptor(
  name='StopRequest',
  full_name='hcfi.StopRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hcfi.StopRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='hcfi.StopRequest.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=296,
)


_STOPRESPONSE = _descriptor.Descriptor(
  name='StopResponse',
  full_name='hcfi.StopResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hcfi.StopResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='solution', full_name='hcfi.StopResponse.solution', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fitness', full_name='hcfi.StopResponse.fitness', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=298,
  serialized_end=359,
)

DESCRIPTOR.message_types_by_name['InitTransactionRequest'] = _INITTRANSACTIONREQUEST
DESCRIPTOR.message_types_by_name['FitnessResponse'] = _FITNESSRESPONSE
DESCRIPTOR.message_types_by_name['FitnessRequest'] = _FITNESSREQUEST
DESCRIPTOR.message_types_by_name['StopRequest'] = _STOPREQUEST
DESCRIPTOR.message_types_by_name['StopResponse'] = _STOPRESPONSE

InitTransactionRequest = _reflection.GeneratedProtocolMessageType('InitTransactionRequest', (_message.Message,), dict(
  DESCRIPTOR = _INITTRANSACTIONREQUEST,
  __module__ = 'hcfi_pb2'
  # @@protoc_insertion_point(class_scope:hcfi.InitTransactionRequest)
  ))
_sym_db.RegisterMessage(InitTransactionRequest)

FitnessResponse = _reflection.GeneratedProtocolMessageType('FitnessResponse', (_message.Message,), dict(
  DESCRIPTOR = _FITNESSRESPONSE,
  __module__ = 'hcfi_pb2'
  # @@protoc_insertion_point(class_scope:hcfi.FitnessResponse)
  ))
_sym_db.RegisterMessage(FitnessResponse)

FitnessRequest = _reflection.GeneratedProtocolMessageType('FitnessRequest', (_message.Message,), dict(
  DESCRIPTOR = _FITNESSREQUEST,
  __module__ = 'hcfi_pb2'
  # @@protoc_insertion_point(class_scope:hcfi.FitnessRequest)
  ))
_sym_db.RegisterMessage(FitnessRequest)

StopRequest = _reflection.GeneratedProtocolMessageType('StopRequest', (_message.Message,), dict(
  DESCRIPTOR = _STOPREQUEST,
  __module__ = 'hcfi_pb2'
  # @@protoc_insertion_point(class_scope:hcfi.StopRequest)
  ))
_sym_db.RegisterMessage(StopRequest)

StopResponse = _reflection.GeneratedProtocolMessageType('StopResponse', (_message.Message,), dict(
  DESCRIPTOR = _STOPRESPONSE,
  __module__ = 'hcfi_pb2'
  # @@protoc_insertion_point(class_scope:hcfi.StopResponse)
  ))
_sym_db.RegisterMessage(StopResponse)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class HillClimberServiceStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.InitTransaction = channel.unary_unary(
          '/hcfi.HillClimberService/InitTransaction',
          request_serializer=InitTransactionRequest.SerializeToString,
          response_deserializer=FitnessResponse.FromString,
          )
      self.SendFitness = channel.unary_unary(
          '/hcfi.HillClimberService/SendFitness',
          request_serializer=FitnessRequest.SerializeToString,
          response_deserializer=FitnessResponse.FromString,
          )
      self.StopTransaction = channel.unary_unary(
          '/hcfi.HillClimberService/StopTransaction',
          request_serializer=StopRequest.SerializeToString,
          response_deserializer=StopResponse.FromString,
          )


  class HillClimberServiceServicer(object):

    def InitTransaction(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def SendFitness(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def StopTransaction(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_HillClimberServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'InitTransaction': grpc.unary_unary_rpc_method_handler(
            servicer.InitTransaction,
            request_deserializer=InitTransactionRequest.FromString,
            response_serializer=FitnessResponse.SerializeToString,
        ),
        'SendFitness': grpc.unary_unary_rpc_method_handler(
            servicer.SendFitness,
            request_deserializer=FitnessRequest.FromString,
            response_serializer=FitnessResponse.SerializeToString,
        ),
        'StopTransaction': grpc.unary_unary_rpc_method_handler(
            servicer.StopTransaction,
            request_deserializer=StopRequest.FromString,
            response_serializer=StopResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'hcfi.HillClimberService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaHillClimberServiceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def InitTransaction(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def SendFitness(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def StopTransaction(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaHillClimberServiceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def InitTransaction(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    InitTransaction.future = None
    def SendFitness(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    SendFitness.future = None
    def StopTransaction(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    StopTransaction.future = None


  def beta_create_HillClimberService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('hcfi.HillClimberService', 'InitTransaction'): InitTransactionRequest.FromString,
      ('hcfi.HillClimberService', 'SendFitness'): FitnessRequest.FromString,
      ('hcfi.HillClimberService', 'StopTransaction'): StopRequest.FromString,
    }
    response_serializers = {
      ('hcfi.HillClimberService', 'InitTransaction'): FitnessResponse.SerializeToString,
      ('hcfi.HillClimberService', 'SendFitness'): FitnessResponse.SerializeToString,
      ('hcfi.HillClimberService', 'StopTransaction'): StopResponse.SerializeToString,
    }
    method_implementations = {
      ('hcfi.HillClimberService', 'InitTransaction'): face_utilities.unary_unary_inline(servicer.InitTransaction),
      ('hcfi.HillClimberService', 'SendFitness'): face_utilities.unary_unary_inline(servicer.SendFitness),
      ('hcfi.HillClimberService', 'StopTransaction'): face_utilities.unary_unary_inline(servicer.StopTransaction),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_HillClimberService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('hcfi.HillClimberService', 'InitTransaction'): InitTransactionRequest.SerializeToString,
      ('hcfi.HillClimberService', 'SendFitness'): FitnessRequest.SerializeToString,
      ('hcfi.HillClimberService', 'StopTransaction'): StopRequest.SerializeToString,
    }
    response_deserializers = {
      ('hcfi.HillClimberService', 'InitTransaction'): FitnessResponse.FromString,
      ('hcfi.HillClimberService', 'SendFitness'): FitnessResponse.FromString,
      ('hcfi.HillClimberService', 'StopTransaction'): StopResponse.FromString,
    }
    cardinalities = {
      'InitTransaction': cardinality.Cardinality.UNARY_UNARY,
      'SendFitness': cardinality.Cardinality.UNARY_UNARY,
      'StopTransaction': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'hcfi.HillClimberService', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
